eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9102/eureka/
server:
  port: 9103

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
